FROM ubuntu:18.04

# docker build -f Dockerfile.ubuntu-18.04 -t ghcr.io/syspack/paks-ubuntu-18.04 .

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Los_Angeles

RUN apt update -y \
      && apt install -y \
      autoconf \
      automake \
      build-essential \
      bzip2 \
      clang \
      cpio \
      curl \
      file \
      findutils \
      g++ \
      gcc \
      gettext \
      gfortran \
      git \
      gpg \
      iputils-ping \
      jq \
      libffi-dev \
      libssl-dev \
      libtool \
      libxml2-dev \
      locales \
      locate \
      m4 \
      make \
      mercurial \
      ncurses-dev \
      patch \
      patchelf \
      pciutils \
      python3-pip \
      rsync \
      unzip \
      wget \
      xz-utils \
      zlib1g-dev \
  && locale-gen en_US.UTF-8 \
  && apt autoremove --purge \
  && apt clean \
  && ln -s /usr/bin/gpg /usr/bin/gpg2

RUN python3 -m pip install --upgrade pip setuptools wheel \
 && python3 -m pip install gnureadline boto3 pyyaml pytz minio requests clingo \
 && rm -rf ~/.cache

# Build all software with debug flags!
ENV SPACK_ADD_DEBUG_FLAGS=true

# Install spack to put on path
RUN git clone https://github.com/spack/spack /opt/spack && \
    /opt/spack/bin/spack compiler find

ENV PATH=/opt/spack/bin:$PATH \
    NVIDIA_VISIBLE_DEVICES=all \
    NVIDIA_DRIVER_CAPABILITIES=compute,utility \
    LANGUAGE=en_US:en \
    LANG=en_US.UTF-8

# Install latest version of Paks
RUN git clone https://github.com/syspack/paks /opt/paks && \
    cd /opt/paks && \
    python3 -m pip install .
   
ENV SPACK_ROOT=/opt/spack    

CMD ["/bin/bash"]
