name: Paks Test Actions
on:
  pull_request: []
  push:
    branches:
      - main 
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    name: Paks Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Package
        uses: ./action/build
        id: build
        with:
          package: zlib
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.actor }}
          deploy: ${{ github.event_name != 'pull_request' }}
