name: Paks Test Building
on:
  pull_request: []
  push:
    branches:
      - main 
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
                    # tag           dockerfile in docker/     platforms
        container: [["18.04"],
                    ["20.04"],
                    ["22.04"]]

    name: Paks Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Package
        if: github.event_name == 'pull_request'
        uses: docker://ghcr.io/syspack/paks-ubuntu-${{ matrix.container[0] }}:latest
        run: paks build zlib

      - name: Build and Deploy Package
        if: github.event_name != 'pull_request'
        uses: docker://ghcr.io/syspack/paks-ubuntu-${{ matrix.container[0] }}:latest
        run: paks build zlib --push ghcr.io/syspack/paks
