name: Paks Test Building
on:
  pull_request: []
  push:
    branches:
      - main 
 
jobs:
  build:
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
                    # tag           dockerfile in docker/     platforms
        container: [["18.04"],
                    ["20.04"]]

    runs-on: ubuntu-latest
    container: ghcr.io/syspack/paks-ubuntu-${{ matrix.container[0] }}:latest
    name: Paks Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Package
        env:
        
          # packages are going to be deployed to pakages org, just testing install here
          deploy: false
          package: zlib
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          uri: ghcr.io/syspack/paks
        run: /entrypoint.sh

      - name: Build Remote Package
        env:
          deploy: false
          package: https://github.com/pakages/zlib
          user: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          uri: ghcr.io/syspack/paks
        run: /entrypoint.sh 
